version: '3.8'
services:
  company_introduction:
    container_name: company_introduction_container
    build: ./
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./reports 
        target: /usr/app/src/reports
    command: bash